export {default as Home} from './home';
export {default as Login} from './login';
export {default as OTP} from './otp';
export {default as SignUp} from './signUp/signUp';
export {default as SplashScreen} from './splash';
export * from './userDetails';
export {default as Onboarding} from './onboarding';
export {default as AmbulanceBooking} from './ambulanceBook';
export {default as HospitalRegistration} from './hospitalRegistration';
export {default as DriverLandingScreen} from './driverScreen';
export {default as HistoryScreen} from './history';
export {default as Setting} from './setting';
